# Generated by Django 3.0.8 on 2020-08-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPL1', '0002_auto_20200805_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='Name',
            field=models.CharField(choices=[('B1', 'Boom 1'), ('B2', 'Boom 2'), ('B3', 'Boom 3'), ('B4', 'Boom 4'), ('B5', 'Boom 5')], default='------', max_length=6),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
