# Generated by Django 3.0.8 on 2020-08-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPL1', '0003_auto_20200805_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('B1', 'Boom 1'), ('B2', 'Boom 2'), ('B3', 'Boom 3'), ('B4', 'Boom 4'), ('B5', 'Boom 5')], default='------', max_length=6)),
                ('Planned_Program', models.IntegerField(default='0')),
                ('Alias', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Program', models.IntegerField(default='0')),
                ('R_Time', models.CharField(max_length=5, null=True)),
                ('R_Data', models.DateField(null=True)),
                ('Sheduled_Program2', models.IntegerField(default='0')),
                ('Alias2', models.CharField(max_length=50)),
                ('R_Time2', models.CharField(max_length=5, null=True)),
                ('R_Data2', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MainTable',
        ),
    ]
