# Generated by Django 3.0.8 on 2020-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPL1', '0004_auto_20200805_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_string',
            old_name='Planned_Program',
            new_name='Program1',
        ),
        migrations.RenameField(
            model_name='device_string',
            old_name='Program',
            new_name='Program2',
        ),
        migrations.RenameField(
            model_name='device_string',
            old_name='Sheduled_Program2',
            new_name='Program3',
        ),
        migrations.AlterField(
            model_name='device_string',
            name='Name',
            field=models.CharField(choices=[('Boom 1', 'Boom 1'), ('Boom 2', 'Boom 2'), ('Boom 3', 'Boom 3'), ('Boom 4', 'Boom 4'), ('Boom 5', 'Boom 5')], default='------', max_length=6),
        ),
    ]
