# Generated by Django 3.0.8 on 2020-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPL1', '0005_auto_20200806_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_string',
            name='id',
        ),
        migrations.AlterField(
            model_name='device_string',
            name='Name',
            field=models.CharField(choices=[('Boom_1', 'Boom-1'), ('Boom_2', 'Boom-2'), ('Boom_3', 'Boom-3'), ('Boom_4', 'Boom-4'), ('Boom_5', 'Boom-5')], default='------', max_length=6, primary_key=True, serialize=False),
        ),
    ]
